victoria-cuomo-tpn1
knnv-ar/la-piscine pull request #19
Opened 2022-11-03 17:56 UTC by viketss

2022-11-03 20:06 UTC, knnv-ar requested changes

2022-11-03 20:06 UTC, knnv-ar commented on _projects/ventanas/statement.md
> +# Título de obra: "Ventanas"
Hola Vic! Fijate que tenés que seguir el modelo de statement.md, que q tiene un encabezado que aquí omitiste. Mirá atentamente el video por favor. Saludos!

2022-11-03 20:06 UTC, knnv-ar commented on _projects/ventanas/statement.md
> +# Título de obra: "Ventanas"
Ah, y tenés que modificar el tamaño de la imagen porque excede los 360 pixeles en alto y ancho.

2022-11-03 20:07 UTC, knnv-ar commented
Vic, fijate por favor las observaciones que te hice en referencia a los archivos statement.md y thumbnail.png.

2022-11-05 13:17 UTC, viketss commented on _projects/ventanas/statement.md
> +# Título de obra: "Ventanas"
Hola Raul! Ya lo arreglo, lo del statement lo hice pero no se me guardó aparentemente, y lo del thumbnail pensé que era del tamaño del canvas. Ando medio despistada jajaja, te lo vuelvo a mandar :)

2022-11-05 13:24 UTC, viketss commented on _projects/ventanas/statement.md
> +# Título de obra: "Ventanas"
Podrás eliminar el anterior? porque no me deja subirlo de nuevo

2022-11-09 15:11 UTC, merged